language: go

go:
  - 1.9
  - master 

install: true

matrix:
  allow_failures:
    - go: master
  fast_finish: true

notifications:
  email: false

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
  - go get github.com/influxdata/influxdb
  - go get github.com/AlekSi/zabbix-sender
  - go get github.com/pelletier/go-toml 
